name: WindowsBuild

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'XingDBG'

    - name: Make dir
      working-directory: ${{github.workspace}}
      shell: cmd
      run: |
        mkdir out
        cd out
        echo test1 >test1.txt
        echo test2 >test2.txt
        mkdir build
        
        
    - name: Pack files
      working-directory: ${{github.workspace}}\out\
      run: |
          &7z a test1.7z test1.txt
          &7z a test2.7z test2.txt
          
    - uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}\out\*.7z

    - uses: xresloader/upload-to-github-release@v1
      if: contains(github.ref, 'tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "out/*.7z"
        overwrite: true
        tags: true
        draft: false
